"use client";

import { useEffect, useMemo, useState } from "react";
import { ArrowDownToLine, ArrowUpRight, Boxes, LoaderCircle, Search, SlidersHorizontal, X } from "lucide-react";
import { createClient } from "@/lib/supabase/client";

type Movement = { id: string; movement_type: "entry" | "delivery" | "return" | "adjustment" | "discard" | "transfer"; quantity: number; notes: string | null; created_at: string; material: { name: string; internal_code: string; unit: string } | null };
const labels: Record<Movement["movement_type"], string> = { entry: "Entrada", delivery: "Entrega", return: "Devolução", adjustment: "Ajuste", discard: "Descarte", transfer: "Transferência" };
const tones: Record<Movement["movement_type"], string> = { entry: "success", delivery: "warning", return: "success", adjustment: "warning", discard: "danger", transfer: "" };
const icons: Record<Movement["movement_type"], typeof ArrowUpRight> = { entry: ArrowUpRight, delivery: ArrowDownToLine, return: ArrowUpRight, adjustment: SlidersHorizontal, discard: ArrowDownToLine, transfer: SlidersHorizontal };

export default function MovementsPage() {
  const [movements, setMovements] = useState<Movement[]>([]);
  const [query, setQuery] = useState("");
  const [filter, setFilter] = useState("all");
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");
  useEffect(() => { async function load() { const { data, error: loadError } = await createClient().from("stock_movements").select("id, movement_type, quantity, notes, created_at, material:materials(name, internal_code, unit)").order("created_at", { ascending: false }).limit(500); if (loadError) setError(loadError.message); else setMovements((data ?? []) as unknown as Movement[]); setLoading(false); } void load(); }, []);
  const filtered = useMemo(() => movements.filter((movement) => (movement.material?.name + " " + movement.material?.internal_code + " " + (movement.notes ?? "")).toLowerCase().includes(query.toLowerCase()) && (filter === "all" || movement.movement_type === filter)), [movements, query, filter]);
  return <main className="module-shell"><header className="module-header"><div><p className="eyebrow">AUDITORIA OPERACIONAL</p><h1>Movimentações</h1><p className="module-subtitle">Acompanhe todas as entradas, entregas, devoluções e saídas do estoque.</p></div></header>{error && <div className="feedback error-feedback"><X size={17} /> {error}</div>}<section className="module-toolbar"><div className="module-search"><Search size={17} /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Buscar material, código ou observação" /></div><select value={filter} onChange={(event) => setFilter(event.target.value)}><option value="all">Todos os tipos</option>{Object.entries(labels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></section><section className="module-summary"><div><strong>{movements.length}</strong><span>movimentações registradas</span></div><div><strong>{movements.filter((item) => item.movement_type === "entry").length}</strong><span>entradas</span></div><div><strong>{movements.filter((item) => item.movement_type === "delivery").length}</strong><span>entregas</span></div><div><strong>{movements.filter((item) => item.movement_type === "return").length}</strong><span>devoluções</span></div></section><section className="panel module-table-card"><div className="panel-header"><div><h2>Histórico do estoque</h2><p>{filtered.length} registro(s) listado(s)</p></div></div>{loading ? <div className="module-loading"><LoaderCircle className="spin" size={22} /> Carregando movimentações...</div> : filtered.length ? <div className="table-wrap"><table><thead><tr><th>DATA</th><th>MATERIAL</th><th>TIPO</th><th>QUANTIDADE</th><th>OBSERVAÇÃO</th></tr></thead><tbody>{filtered.map((movement) => { const Icon = icons[movement.movement_type]; return <tr key={movement.id}><td>{new Date(movement.created_at).toLocaleString("pt-BR", { dateStyle: "short", timeStyle: "short" })}</td><td><div className="material-cell"><div className="material-type-icon epi"><Boxes size={17} /></div><div><strong>{movement.material?.name ?? "Material removido"}</strong><small>{movement.material?.internal_code} · {movement.material?.unit}</small></div></div></td><td><span className={"movement-type " + tones[movement.movement_type]}><Icon size={14} /> {labels[movement.movement_type]}</span></td><td><strong>{movement.quantity}</strong> {movement.material?.unit}</td><td>{movement.notes || <span className="muted-cell">Sem observação</span>}</td></tr>; })}</tbody></table></div> : <div className="empty-state"><SlidersHorizontal size={27} /><strong>Nenhuma movimentação encontrada</strong><span>Os registros aparecerão aqui conforme o estoque for movimentado.</span></div>}</section></main>;
}

