"use client";

import { FormEvent, useState } from "react";
import { ArrowRight, Check, ShieldCheck } from "lucide-react";
import { useParams, useRouter } from "next/navigation";
import { createClient } from "@/lib/supabase/client";

export default function InvitePage() {
  const { token } = useParams<{ token: string }>(); const router = useRouter(); const [name, setName] = useState(""); const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [error, setError] = useState(""); const [success, setSuccess] = useState(""); const [saving, setSaving] = useState(false);
  async function submit(event: FormEvent) { event.preventDefault(); if (password.length < 6) { setError("A senha deve ter pelo menos 6 caracteres."); return; } setSaving(true); setError(""); try { const supabase = createClient(); const { data, error: signUpError } = await supabase.auth.signUp({ email: email.trim(), password, options: { data: { full_name: name.trim() } } }); if (signUpError) { setError(signUpError.message); return; } if (!data.session) { setSuccess("Conta criada. Confirme o e-mail, entre no sistema e abra este mesmo link novamente para concluir o convite."); return; } const { error: acceptError } = await supabase.rpc("accept_organization_invitation", { p_token: token, p_full_name: name.trim() }); if (acceptError) { setError(acceptError.message); return; } setSuccess("Convite aceito. Seu acesso foi configurado."); window.setTimeout(() => router.replace("/"), 700); } finally { setSaving(false); } }
  return <main className="login-shell"><div className="login-brand"><div className="brand-mark"><ShieldCheck size={25} /></div><div><strong>EPIS<span>+</span></strong><small>Gestão inteligente</small></div></div><section className="login-card" aria-labelledby="invite-title"><p className="eyebrow">CONVITE DE ORGANIZAÇÃO</p><h1 id="invite-title">Criar acesso</h1><p className="login-subtitle">Preencha seus dados para entrar na organização convidante.</p><form onSubmit={submit}><label>Nome completo<input value={name} onChange={(event) => setName(event.target.value)} required autoComplete="name" /></label><label>E-mail<input type="email" value={email} onChange={(event) => setEmail(event.target.value)} required autoComplete="email" /></label><label>Senha<input type="password" value={password} onChange={(event) => setPassword(event.target.value)} required minLength={6} autoComplete="new-password" /></label>{error && <p className="login-error" role="alert">{error}</p>}{success && <p className="login-success" role="status"><Check size={15} /> {success}</p>}<button className="primary-button login-button" type="submit" disabled={saving}>{saving ? "Criando acesso..." : "Aceitar convite"}<ArrowRight size={17} /></button></form></section></main>;
}
