"use client";

import { useEffect, useState } from "react";
import { ClipboardList, LoaderCircle, Search } from "lucide-react";
import { createClient } from "@/lib/supabase/client";
type Audit = { id: string; action: string; table_name: string; record_id: string | null; created_at: string; actor_id: string | null };
const labels: Record<string, string> = { insert: "CriaÃ§Ã£o", update: "AlteraÃ§Ã£o", delete: "ExclusÃ£o" };
export default function AuditPage() { const [rows, setRows] = useState<Audit[]>([]); const [query, setQuery] = useState(""); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); useEffect(() => { async function load() { const { data, error: loadError } = await createClient().from("audit_logs").select("id,action,table_name,record_id,created_at,actor_id").order("created_at", { ascending: false }).limit(200); if (loadError) setError(loadError.message); else setRows((data ?? []) as Audit[]); setLoading(false); } void load(); }, []); const filtered = rows.filter((row) => `${row.action} ${row.table_name} ${row.record_id ?? ""}`.toLowerCase().includes(query.toLowerCase())); return <main className="module-shell"><header className="module-header"><div><p className="eyebrow">SEGURANÃ‡A E CONTROLE</p><h1>Auditoria</h1><p className="module-subtitle">Consulte as alteraÃ§Ãµes realizadas nos dados do sistema.</p></div></header><section className="module-toolbar"><div className="module-search"><Search size={17} /><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Buscar por aÃ§Ã£o, tabela ou identificador" /></div></section><section className="panel module-table-card">{error && <div className="feedback error-feedback">{error}</div>}{loading ? <div className="module-loading"><LoaderCircle className="spin" size={22} /> Carregando auditoria...</div> : <div className="table-wrap"><table><thead><tr><th>DATA</th><th>AÃ‡ÃƒO</th><th>TABELA</th><th>REGISTRO</th><th>USUÃRIO</th></tr></thead><tbody>{filtered.map((row) => <tr key={row.id}><td>{new Date(row.created_at).toLocaleString("pt-BR")}</td><td><span className="movement-type">{labels[row.action] || row.action}</span></td><td>{row.table_name}</td><td>{row.record_id || "â€”"}</td><td>{row.actor_id || "Sistema"}</td></tr>)}</tbody></table>{!filtered.length && <div className="empty-state"><ClipboardList size={27} /><strong>Nenhum registro encontrado</strong><span>As novas alteraÃ§Ãµes aparecerÃ£o aqui automaticamente.</span></div>}</div>}</section></main>; }

