"use client";

import { FormEvent, useState } from "react";
import { Check, LoaderCircle, LogIn, Ruler, ShieldCheck, X } from "lucide-react";

const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL ?? "https://uedqxkzprueezjarhzql.supabase.co";
const supabasePublishableKey = process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY ?? "sb_publishable_9l2tSpFY9qHdAysv4P4ECw_rzqqgDbY";
type PortalProfile = { employee_id: string; employee_name: string; function_name: string; organization_name: string; shirt_size: string | null; pants_size: string | null; shoe_size: string | null; helmet_size: string | null; glove_size: string | null; uniform_notes: string | null };
type Form = { shirt: string; pants: string; shoe: string; helmet: string; glove: string; notes: string };
const emptyForm: Form = { shirt: "", pants: "", shoe: "", helmet: "", glove: "", notes: "" };

async function portalRpc<T>(name: string, body: Record<string, unknown>) { const response = await fetch(`${supabaseUrl}/rest/v1/rpc/${name}`, { method: "POST", headers: { apikey: supabasePublishableKey, Authorization: `Bearer ${supabasePublishableKey}`, "Content-Type": "application/json" }, body: JSON.stringify(body) }); if (!response.ok) throw new Error("Não foi possível validar os dados."); return response.json() as Promise<T>; }

export default function EmployeePortalPage() {
  const [registration, setRegistration] = useState(""); const [cpf, setCpf] = useState(""); const [profile, setProfile] = useState<PortalProfile | null>(null); const [form, setForm] = useState<Form>(emptyForm); const [loading, setLoading] = useState(false); const [saving, setSaving] = useState(false); const [success, setSuccess] = useState(false); const [error, setError] = useState("");
  async function login(event: FormEvent) { event.preventDefault(); setLoading(true); setError(""); try { const data = await portalRpc<PortalProfile[]>("get_employee_portal", { p_registration: registration, p_cpf: cpf }); const row = data?.[0]; if (!row) setError("Matrícula ou CPF não conferem."); else { setProfile(row); setForm({ shirt: row.shirt_size ?? "", pants: row.pants_size ?? "", shoe: row.shoe_size ?? "", helmet: row.helmet_size ?? "", glove: row.glove_size ?? "", notes: row.uniform_notes ?? "" }); } } catch { setError("Não foi possível acessar o portal. Tente novamente."); } setLoading(false); }
  async function save(event: FormEvent) { event.preventDefault(); if (!profile) return; setSaving(true); setError(""); setSuccess(false); try { await portalRpc("submit_employee_portal_measurements", { p_registration: registration, p_cpf: cpf, p_shirt_size: form.shirt, p_pants_size: form.pants, p_shoe_size: form.shoe, p_helmet_size: form.helmet, p_glove_size: form.glove, p_notes: form.notes }); setSuccess(true); } catch { setError("Não foi possível salvar suas medidas."); } setSaving(false); }
  function update(field: keyof Form, value: string) { setForm((current) => ({ ...current, [field]: value })); }
  return <main className="employee-portal"><section className="employee-portal-card"><div className="public-brand"><ShieldCheck size={22} /><strong>EPIS<span>+</span></strong></div>{!profile ? <><div className="public-title"><LogIn size={26} /><p>PORTAL DO COLABORADOR</p><h1>Acesse sua ficha</h1><span>Informe sua matrícula e CPF para consultar e preencher seus dados.</span></div><form className="material-form public-form" onSubmit={login}><label>Matrícula<input value={registration} onChange={(event) => setRegistration(event.target.value)} placeholder="Ex.: 0123" required /></label><label>CPF<input value={cpf} onChange={(event) => setCpf(event.target.value)} inputMode="numeric" placeholder="000.000.000-00" required /></label>{error && <div className="public-feedback error-feedback"><X size={18} /> {error}</div>}<button className="primary-button" disabled={loading}>{loading ? <><LoaderCircle className="spin" size={17} /> Validando...</> : <>Entrar no portal <LogIn size={16} /></>}</button></form></> : <><div className="public-title"><Ruler size={26} /><p>{profile.organization_name || "PORTAL DO COLABORADOR"}</p><h1>Olá, {profile.employee_name}</h1><span>{profile.function_name || "Função não informada"}</span></div><form className="material-form public-form" onSubmit={save}><div className="form-grid two"><label>Camiseta / uniforme<input value={form.shirt} onChange={(event) => update("shirt", event.target.value)} placeholder="Ex.: M" /></label><label>Calça<input value={form.pants} onChange={(event) => update("pants", event.target.value)} placeholder="Ex.: 42" /></label></div><div className="form-grid three"><label>Calçado / botina<input value={form.shoe} onChange={(event) => update("shoe", event.target.value)} placeholder="Ex.: 40" /></label><label>Capacete<input value={form.helmet} onChange={(event) => update("helmet", event.target.value)} placeholder="Ex.: 58" /></label><label>Luvas<input value={form.glove} onChange={(event) => update("glove", event.target.value)} placeholder="Ex.: 9 / G" /></label></div><label>Observações<textarea value={form.notes} onChange={(event) => update("notes", event.target.value)} rows={3} placeholder="Preferências ou medidas especiais" /></label>{success && <div className="public-feedback success-feedback"><Check size={18} /> Medidas salvas com sucesso.</div>}{error && <div className="public-feedback error-feedback"><X size={18} /> {error}</div>}<button className="primary-button" disabled={saving}>{saving ? "Salvando..." : "Salvar minhas medidas"}<Check size={16} /></button></form><button className="portal-logout" type="button" onClick={() => { setProfile(null); setSuccess(false); setError(""); }}>Sair</button></>}</section></main>;
}
