"use client";

import { FormEvent, useState } from "react";
import { useRouter } from "next/navigation";
import { ArrowRight, ShieldCheck } from "lucide-react";
import { createClient } from "@/lib/supabase/client";
import { friendlyError } from "@/lib/ui-feedback";

export default function LoginPage() {
  const router = useRouter(); const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [error, setError] = useState(""); const [loading, setLoading] = useState(false); const [resetSent, setResetSent] = useState(false);
  async function onSubmit(event: FormEvent) { event.preventDefault(); setLoading(true); setError(""); const supabase = createClient(); const { error: signInError } = await supabase.auth.signInWithPassword({ email, password }); if (signInError) setError("E-mail ou senha inválidos."); else router.push("/"); setLoading(false); }
  async function requestReset() { setError(""); setResetSent(false); if (!email) { setError("Informe seu e-mail para receber o link."); return; } const { error: resetError } = await createClient().auth.resetPasswordForEmail(email, { redirectTo: `${window.location.origin}/reset-password` }); if (resetError) setError(friendlyError(resetError, "Não foi possível concluir a operação.")); else setResetSent(true); }
  return <main className="login-shell"><div className="login-brand"><div className="brand-mark" aria-hidden="true"><ShieldCheck size={25} /></div><div><strong>EPIS<span>+</span></strong><small>Gestão inteligente</small></div></div><section className="login-card" aria-labelledby="login-title"><p className="eyebrow">ACESSO RESTRITO</p><h1 id="login-title">Bem-vindo de volta</h1><p className="login-subtitle">Entre para acessar o controle de equipamentos da sua empresa.</p><form onSubmit={onSubmit}><label htmlFor="login-email">E-mail<input id="login-email" name="email" type="email" autoComplete="email" value={email} onChange={(e) => setEmail(e.target.value)} placeholder="seu@email.com" required /></label><label htmlFor="login-password">Senha<input id="login-password" name="password" type="password" autoComplete="current-password" value={password} onChange={(e) => setPassword(e.target.value)} placeholder="Digite sua senha" required /></label>{error && <p id="login-error" className="login-error" role="alert" aria-live="assertive">{error}</p>}{resetSent && <p id="login-success" className="login-success" role="status" aria-live="polite">Link de redefinição enviado. Verifique seu e-mail.</p>}<button className="primary-button login-button" type="submit" disabled={loading} aria-busy={loading}>{loading ? "Entrando..." : "Entrar"}<ArrowRight size={17} aria-hidden="true" /></button></form><button className="text-button" type="button" onClick={requestReset} disabled={loading}>Esqueci minha senha</button><p className="login-footer">Acesso protegido por Supabase Auth</p></section></main>;
}
