"use client";

import { FormEvent, useEffect, useState } from "react";
import { ArrowLeft, Check, ClipboardCheck, X } from "lucide-react";
import Link from "next/link";
import { createClient } from "@/lib/supabase/client";

type Employee = { id: string; full_name: string; registration: string };
type DeliveredItem = { id: string; quantity: number; returned: number; material: { name: string; internal_code: string; unit: string } | null; delivery: { employee_id: string; delivered_at: string; employee: { full_name: string; registration: string } | null } | null };

const reasons = [["replacement", "SubstituiÃ§Ã£o"], ["termination", "Desligamento"], ["role_change", "AlteraÃ§Ã£o de funÃ§Ã£o"], ["damaged", "Equipamento danificado"], ["other", "Outro"]];

export default function ReturnsPage() {
  const [employees, setEmployees] = useState<Employee[]>([]); const [items, setItems] = useState<DeliveredItem[]>([]); const [employeeId, setEmployeeId] = useState(""); const [itemId, setItemId] = useState(""); const [quantity, setQuantity] = useState("1"); const [reason, setReason] = useState("replacement"); const [returnedAt, setReturnedAt] = useState(new Date().toISOString().slice(0, 10)); const [notes, setNotes] = useState(""); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [error, setError] = useState(""); const [success, setSuccess] = useState("");
  async function loadData() { const supabase = createClient(); const [{ data: employeeData, error: employeeError }, { data: itemData, error: itemError }, { data: returnData, error: returnError }] = await Promise.all([supabase.from("employees").select("id, full_name, registration").order("full_name"), supabase.from("delivery_items").select("id, quantity, material:materials(name, internal_code, unit), delivery:deliveries(employee_id, delivered_at, employee:employees(full_name, registration))").order("created_at", { ascending: false }), supabase.from("return_items").select("delivery_item_id, quantity")]); if (employeeError || itemError || returnError) setError((employeeError ?? itemError ?? returnError)?.message ?? "NÃ£o foi possÃ­vel carregar os dados."); else { const returnedByItem = new Map<string, number>(); (returnData ?? []).forEach((item) => returnedByItem.set(item.delivery_item_id, (returnedByItem.get(item.delivery_item_id) ?? 0) + item.quantity)); setEmployees((employeeData ?? []) as Employee[]); setItems(((itemData ?? []) as unknown as DeliveredItem[]).map((item) => ({ ...item, returned: returnedByItem.get(item.id) ?? 0 }))); } setLoading(false); }
  useEffect(() => { void Promise.resolve().then(() => loadData()); }, []);
  const employeeItems = items.filter((item) => item.delivery?.employee_id === employeeId && item.quantity > item.returned);
  async function submit(event: FormEvent) { event.preventDefault(); setError(""); setSuccess(""); const selected = items.find((item) => item.id === itemId); if (!employeeId || !selected) { setError("Selecione o funcionÃ¡rio e o equipamento devolvido."); return; } if (Number(quantity) <= 0 || Number(quantity) > selected.quantity - selected.returned) { setError("Informe uma quantidade vÃ¡lida para a devoluÃ§Ã£o."); return; } setSaving(true); const { error: returnError } = await createClient().rpc("register_return", { p_employee_id: employeeId, p_reason: reason, p_returned_at: returnedAt || null, p_items: [{ delivery_item_id: itemId, quantity: Number(quantity) }], p_notes: notes || null }); if (returnError) setError(returnError.message); else { setSuccess("DevoluÃ§Ã£o registrada e quantidade reintegrada ao estoque."); setEmployeeId(""); setItemId(""); setQuantity("1"); setNotes(""); await loadData(); } setSaving(false); }
  return <main className="module-shell"><header className="module-header"><div><p className="eyebrow">MOVIMENTAÃ‡ÃƒO DE EQUIPAMENTOS</p><h1>DevoluÃ§Ãµes</h1><p className="module-subtitle">Registre equipamentos devolvidos e reintegre-os ao estoque.</p></div><Link className="secondary-button" href="/deliveries"><ArrowLeft size={16} /> Entregas</Link></header>{success && <div className="feedback success-feedback"><Check size={17} /> {success}</div>}{error && <div className="feedback error-feedback"><X size={17} /> {error}</div>}<section className="panel entry-card delivery-card"><div className="entry-intro"><div className="entry-icon"><ClipboardCheck size={22} /></div><div><h2>Ficha de devoluÃ§Ã£o</h2><p>O item serÃ¡ devolvido ao mesmo lote de origem da entrega.</p></div></div><form className="material-form" onSubmit={submit}><div className="form-grid two"><label>FuncionÃ¡rio<select value={employeeId} onChange={(event) => { setEmployeeId(event.target.value); setItemId(""); }} required disabled={loading}><option value="">Selecione um funcionÃ¡rio</option>{employees.map((employee) => <option key={employee.id} value={employee.id}>{employee.registration} Â· {employee.full_name}</option>)}</select></label><label>Equipamento<select value={itemId} onChange={(event) => setItemId(event.target.value)} required disabled={!employeeId || loading}><option value="">Selecione o equipamento</option>{employeeItems.map((item) => <option key={item.id} value={item.id}>{item.material?.internal_code} Â· {item.material?.name} ({item.quantity - item.returned} disponÃ­veis)</option>)}</select></label></div><div className="form-grid three"><label>Quantidade<input type="number" min="1" value={quantity} onChange={(event) => setQuantity(event.target.value)} required /></label><label>Data da devoluÃ§Ã£o<input type="date" value={returnedAt} onChange={(event) => setReturnedAt(event.target.value)} required /></label><label>Motivo<select value={reason} onChange={(event) => setReason(event.target.value)}>{reasons.map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label></div><label>ObservaÃ§Ãµes<textarea value={notes} onChange={(event) => setNotes(event.target.value)} placeholder="CondiÃ§Ã£o do equipamento ou observaÃ§Ãµes" rows={3} /></label><div className="modal-actions"><Link className="secondary-button" href="/stock">Consultar estoque</Link><button className="primary-button" disabled={saving || loading || !items.length}>{saving ? "Registrando..." : "Confirmar devoluÃ§Ã£o"}<Check size={16} /></button></div></form></section></main>;
}

