"use client";

import { useEffect, useMemo, useState } from "react";
import { CalendarClock, LoaderCircle, Search, ShieldCheck, X } from "lucide-react";
import { createClient } from "@/lib/supabase/client";

type Lot = { id: string; lot_number: string; available_quantity: number; expires_at: string | null; material: { name: string; internal_code: string; type: "EPI" | "EPC"; unit: string } | null };
function daysUntil(value: string | null) { if (!value) return null; return Math.ceil((new Date(`${value}T00:00:00`).getTime() - new Date(new Date().toDateString()).getTime()) / 86400000); }

export default function ValiditiesPage() { const [lots, setLots] = useState<Lot[]>([]); const [query, setQuery] = useState(""); const [filter, setFilter] = useState("all"); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  useEffect(() => { void Promise.resolve().then(async () => { const { data, error: loadError } = await createClient().from("material_lots").select("id, lot_number, available_quantity, expires_at, material:materials(name, internal_code, type, unit)").gt("available_quantity", 0).order("expires_at", { ascending: true, nullsFirst: false }); if (loadError) setError(loadError.message); else setLots((data ?? []) as unknown as Lot[]); setLoading(false); }); }, []);
  const filtered = useMemo(() => lots.filter((lot) => { const days = daysUntil(lot.expires_at); const text = `${lot.material?.name} ${lot.material?.internal_code} ${lot.lot_number}`.toLowerCase(); const matchesQuery = text.includes(query.toLowerCase()); const matchesFilter = filter === "all" || (filter === "expired" && days !== null && days < 0) || (filter === "urgent" && days !== null && days >= 0 && days <= 30) || (filter === "ok" && (days === null || days > 30)); return matchesQuery && matchesFilter; }), [lots, query, filter]);
  const counts = { expired: lots.filter((lot) => (daysUntil(lot.expires_at) ?? 9999) < 0).length, urgent: lots.filter((lot) => { const days = daysUntil(lot.expires_at); return days !== null && days >= 0 && days <= 30; }).length, without: lots.filter((lot) => !lot.expires_at).length };
  return <main className="module-shell"><header className="module-header"><div><p className="eyebrow">CONTROLE OPERACIONAL</p><h1>Validades</h1><p className="module-subtitle">Acompanhe lotes próximos do vencimento e planeje substituições.</p></div></header>{error && <div className="feedback error-feedback"><X size={17} /> {error}</div>}<section className="module-toolbar"><div className="module-search"><Search size={17} /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Buscar material ou lote" /></div><select value={filter} onChange={(event) => setFilter(event.target.value)}><option value="all">Todas as validades</option><option value="expired">Vencidos</option><option value="urgent">Até 30 dias</option><option value="ok">Mais de 30 dias / sem data</option></select></section><section className="module-summary"><div><strong>{lots.length}</strong><span>lotes com saldo</span></div><div><strong>{counts.expired}</strong><span>vencidos</span></div><div><strong>{counts.urgent}</strong><span>até 30 dias</span></div><div><strong>{counts.without}</strong><span>sem validade</span></div></section><section className="panel module-table-card"><div className="panel-header"><div><h2>Calendário de validades</h2><p>{filtered.length} lote(s) listado(s)</p></div></div>{loading ? <div className="module-loading"><LoaderCircle className="spin" size={22} /> Carregando validades...</div> : filtered.length ? <div className="table-wrap"><table><thead><tr><th>MATERIAL</th><th>LOTE</th><th>SALDO</th><th>VALIDADE</th><th>SITUAÇÃO</th></tr></thead><tbody>{filtered.map((lot) => { const days = daysUntil(lot.expires_at); const expired = days !== null && days < 0; const urgent = days !== null && days >= 0 && days <= 30; const label = days === null ? "Sem data" : expired ? `Vencido há ${Math.abs(days)} dia(s)` : days === 0 ? "Vence hoje" : `Vence em ${days} dia(s)`; return <tr key={lot.id}><td><div className="material-cell"><div className={`material-type-icon ${lot.material?.type === "EPC" ? "epc" : "epi"}`}><CalendarClock size={17} /></div><div><strong>{lot.material?.name ?? "Material removido"}</strong><small>{lot.material?.internal_code} · {lot.material?.type}</small></div></div></td><td>{lot.lot_number}</td><td><strong>{lot.available_quantity}</strong> {lot.material?.unit}</td><td>{lot.expires_at ? new Date(`${lot.expires_at}T00:00:00`).toLocaleDateString("pt-BR") : <span className="muted-cell">Não informado</span>}</td><td><span className={`status-pill ${expired ? "danger" : urgent ? "warning" : lot.expires_at ? "success" : "warning"}`}>{label}</span></td></tr>; })}</tbody></table></div> : <div className="empty-state"><ShieldCheck size={27} /><strong>Nenhum lote encontrado</strong><span>Não há lotes com saldo para os filtros selecionados.</span></div>}</section></main>;
}
