"use client";

import { AlertTriangle, ArrowDownToLine, ArrowUpRight, Bell, Boxes, CalendarClock, ChevronDown, CircleHelp, ClipboardList, LayoutDashboard, Menu, PackageCheck, Search, Settings, ShieldCheck, SlidersHorizontal, Users, X } from "lucide-react";
import { useState } from "react";

const menu = [
  ["Dashboard", LayoutDashboard], ["Materiais", Boxes], ["Funcionários", Users], ["Entregas", ArrowUpRight], ["Devoluções", ArrowDownToLine], ["Estoque", PackageCheck], ["Entradas", ClipboardList], ["Validades", CalendarClock], ["CA", ShieldCheck], ["Relatórios", ClipboardList], ["Movimentações", SlidersHorizontal],
] as const;
const deliveries = [
  ["Mariana Costa", "Técnica de Segurança", "Luva Vaqueta", "2 pares", "Hoje, 09:42", "MC", "lavender"], ["Rafael Mendes", "Operador de Produção", "Capacete Classe B", "1 un.", "Hoje, 08:17", "RM", "peach"], ["João da Silva", "Eletricista", "Botina de Segurança", "1 par", "Ontem, 16:35", "JS", "blue"], ["Ana Paula Reis", "Auxiliar de Logística", "Protetor auricular", "1 un.", "Ontem, 14:09", "AR", "mint"],
];
const stock = [["Luva Vaqueta", "EPI-00042", 18, 25, "pares", "Baixo", "warning"], ["Capacete Classe B", "EPI-00017", 64, 20, "un.", "Normal", "success"], ["Botina de Segurança", "EPI-00031", 0, 15, "pares", "Sem estoque", "danger"], ["Protetor auricular", "EPI-00009", 42, 30, "un.", "Normal", "success"]];

function Metric({ icon: Icon, label, value, detail, tone }: { icon: typeof Boxes; label: string; value: string; detail: string; tone: string }) { return <div className="metric-card"><div className={`metric-icon ${tone}`}><Icon size={20} /></div><div className="metric-copy"><span>{label}</span><strong>{value}</strong><small>{detail}</small></div></div>; }

export default function Home() {
  const [mobileMenu, setMobileMenu] = useState(false);
  return <div className="app-shell">
    <aside className={`sidebar ${mobileMenu ? "open" : ""}`}><div className="brand"><div className="brand-mark"><ShieldCheck size={22} /></div><div><strong>EPIS<span>+</span></strong><small>Gestão inteligente</small></div><button className="close-menu" onClick={() => setMobileMenu(false)}><X size={20} /></button></div><div className="workspace-label">MENU PRINCIPAL</div><nav>{menu.map(([label, Icon], index) => <a className={index === 0 ? "active" : ""} href="#" key={label} onClick={() => setMobileMenu(false)}><Icon size={18} /><span>{label}</span>{label === "Validades" && <b className="nav-count">5</b>}</a>)}</nav><div className="sidebar-bottom"><a href="#"><Settings size={18} /><span>Configurações</span></a><a href="#"><CircleHelp size={18} /><span>Central de ajuda</span></a><div className="user-mini"><div className="avatar avatar-dark">AS</div><div><strong>André Santos</strong><small>Administrador</small></div><ChevronDown size={15} /></div></div></aside>
    <main className="main-content"><header className="topbar"><button className="menu-toggle" onClick={() => setMobileMenu(true)}><Menu size={22} /></button><div className="breadcrumb"><span>Visão geral</span><span>/</span><strong>Dashboard</strong></div><div className="top-actions"><div className="search"><Search size={18} /><input placeholder="Buscar materiais, funcionários..." /></div><button className="icon-button notification"><Bell size={19} /><i /></button><div className="profile"><div className="avatar avatar-blue">AS</div><div><strong>André Santos</strong><small>Administrador</small></div><ChevronDown size={15} /></div></div></header>
      <div className="page-content"><section className="welcome"><div><p className="eyebrow">TERÇA-FEIRA, 02 DE SETEMBRO DE 2026</p><h1>Bom dia, André <span>👋</span></h1><p className="subtitle">Aqui está um resumo do que está acontecendo na sua operação hoje.</p></div><button className="primary-button"><ArrowUpRight size={17} /> Nova entrega</button></section>
        <section className="metrics-grid"><Metric icon={Boxes} label="Materiais cadastrados" value="128" detail="84 EPIs · 44 EPCs" tone="purple" /><Metric icon={Users} label="Funcionários ativos" value="247" detail="+12 este mês" tone="blue" /><Metric icon={PackageCheck} label="Itens em estoque" value="1.842" detail="Em 36 lotes ativos" tone="green" /><Metric icon={AlertTriangle} label="Alertas pendentes" value="12" detail="5 críticos · 7 atenção" tone="orange" /></section>
        <section className="dashboard-grid"><div className="panel delivery-chart"><div className="panel-header"><div><h2>Entregas realizadas</h2><p>Movimentação dos últimos 12 meses</p></div><button className="select-button">Últimos 12 meses <ChevronDown size={15} /></button></div><div className="chart-legend"><span><i className="dot purple-dot" /> EPIs</span><span><i className="dot blue-dot" /> EPCs</span></div><div className="chart"><div className="y-axis"><span>120</span><span>90</span><span>60</span><span>30</span><span>0</span></div><div className="chart-area"><div className="gridline g1" /><div className="gridline g2" /><div className="gridline g3" /><div className="gridline g4" /><svg viewBox="0 0 700 190" preserveAspectRatio="none" className="chart-svg"><defs><linearGradient id="areaPurple" x1="0" x2="0" y1="0" y2="1"><stop offset="0" stopColor="#8973e7" stopOpacity=".2" /><stop offset="1" stopColor="#8973e7" stopOpacity="0" /></linearGradient></defs><path d="M0 145 C30 135 35 116 64 120 S96 141 128 104 S168 77 192 94 S232 90 256 65 S298 81 320 66 S360 62 384 72 S420 38 448 58 S488 84 512 48 S556 65 576 34 S625 55 640 29 S680 38 700 19 L700 190 L0 190 Z" fill="url(#areaPurple)" /><path d="M0 145 C30 135 35 116 64 120 S96 141 128 104 S168 77 192 94 S232 90 256 65 S298 81 320 66 S360 62 384 72 S420 38 448 58 S488 84 512 48 S556 65 576 34 S625 55 640 29 S680 38 700 19" fill="none" stroke="#7762d6" strokeWidth="3" strokeLinecap="round" /><path d="M0 164 C32 158 42 148 64 154 S108 159 128 140 S165 124 192 139 S230 130 256 119 S295 126 320 107 S360 125 384 113 S422 107 448 110 S485 127 512 98 S555 112 576 97 S620 110 640 83 S679 97 700 74" fill="none" stroke="#4c9ed9" strokeWidth="2.5" strokeDasharray="6 5" strokeLinecap="round" /></svg><div className="x-axis"><span>Out</span><span>Nov</span><span>Dez</span><span>Jan</span><span>Fev</span><span>Mar</span><span>Abr</span><span>Mai</span><span>Jun</span><span>Jul</span><span>Ago</span><span>Set</span></div></div></div></div>
          <div className="panel alerts"><div className="panel-header"><div><h2>Alertas importantes</h2><p>Requerem sua atenção</p></div><button className="more-button">•••</button></div><div className="alert-list"><div className="alert-item critical"><div className="alert-icon"><AlertTriangle size={17} /></div><div><strong>Estoque abaixo do mínimo</strong><p>Luva Vaqueta · 18 pares disponíveis</p></div><ChevronDown size={15} /></div><div className="alert-item"><div className="alert-icon calendar"><CalendarClock size={17} /></div><div><strong>CA vencendo em breve</strong><p>CA 42.781 · Capacete Classe B · 15 dias</p></div><ChevronDown size={15} /></div><div className="alert-item"><div className="alert-icon swap"><CalendarClock size={17} /></div><div><strong>Troca programada</strong><p>3 equipamentos vencem nos próximos 7 dias</p></div><ChevronDown size={15} /></div></div><button className="view-all">Ver todos os alertas <ArrowUpRight size={15} /></button></div></section>
        <section className="bottom-grid"><div className="panel recent-deliveries"><div className="panel-header"><div><h2>Entregas recentes</h2><p>Últimas movimentações registradas</p></div><a href="#" className="text-link">Ver todas <ArrowUpRight size={15} /></a></div><div className="table-wrap"><table><thead><tr><th>FUNCIONÁRIO</th><th>EQUIPAMENTO</th><th>QTD.</th><th>DATA</th><th>STATUS</th></tr></thead><tbody>{deliveries.map(([name, role, item, qty, time, initials, tone]) => <tr key={name}><td><div className="person"><div className={`avatar avatar-${tone}`}>{initials}</div><div><strong>{name}</strong><small>{role}</small></div></div></td><td>{item}</td><td>{qty}</td><td>{time}</td><td><span className="status-pill delivered">Entregue</span></td></tr>)}</tbody></table></div></div><div className="panel stock-panel"><div className="panel-header"><div><h2>Situação do estoque</h2><p>Visão rápida por material</p></div><a href="#" className="text-link">Ver estoque <ArrowUpRight size={15} /></a></div><div className="stock-list">{stock.map(([name, code, current, minimum, unit, status, tone]) => <div className="stock-row" key={code}><div className="stock-info"><div className="material-icon"><Boxes size={17} /></div><div><strong>{name}</strong><small>{code}</small></div></div><div className="stock-quantity"><strong>{current}</strong><small>/ {minimum} {unit}</small></div><span className={`status-pill ${tone}`}>{status}</span></div>)}</div></div></section><footer>EPIS+ Gestão inteligente de equipamentos <span>·</span> Última atualização: agora</footer></div>
    </main></div>;
}

