"use client";

import { ClipboardCheck, FileWarning, LoaderCircle, PackageCheck, ShieldAlert } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import { createClient } from "@/lib/supabase/client";

type Row = { id: string; source_annex: string; quantity: number; material: { id: string; name: string; contract_item_code: string | null; ca_required: boolean; ca_number: string | null; ca_expires_at: string | null; test_required: boolean } | null; scenario: { active: boolean } };
type Lot = { material_id: string; available_quantity: number };

export default function CompliancePage() {
  const [rows, setRows] = useState<Row[]>([]); const [stock, setStock] = useState<Record<string, number>>({}); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  useEffect(() => { async function load() { const supabase = createClient(); const [{ data: requirementData, error: requirementError }, { data: lotData, error: lotError }] = await Promise.all([supabase.from("contract_requirements").select("id,source_annex,quantity,scenario:contract_scenarios!inner(active),material:materials(id,name,contract_item_code,ca_required,ca_number,ca_expires_at,test_required)"), supabase.from("material_lots").select("material_id,available_quantity")]); if (requirementError || lotError) setError((requirementError ?? lotError)?.message ?? "Não foi possível carregar a conformidade."); setRows((requirementData ?? []) as unknown as Row[]); setStock((lotData ?? []).reduce<Record<string, number>>((sum, lot: Lot) => ({ ...sum, [lot.material_id]: (sum[lot.material_id] ?? 0) + Number(lot.available_quantity) }), {})); setLoading(false); } void load(); }, []);
  const uniqueMaterials = useMemo(() => Array.from(new Map(rows.filter((row) => row.material).map((row) => [row.material!.id, row.material!])).values()), [rows]);
  const stockIssues = rows.filter((row) => row.material && (stock[row.material.id] ?? 0) < Number(row.quantity)).length;
  const caIssues = uniqueMaterials.filter((material) => material.ca_required && (!material.ca_number || material.ca_number === "PENDENTE" || (material.ca_expires_at && material.ca_expires_at < new Date().toISOString().slice(0, 10)))).length;
  const testIssues = uniqueMaterials.filter((material) => material.test_required).length;
  const byAnnex = Array.from(new Set(rows.map((row) => row.source_annex))).map((annex) => ({ annex, count: rows.filter((row) => row.source_annex === annex).length, missing: rows.filter((row) => row.source_annex === annex && row.material && (stock[row.material.id] ?? 0) < Number(row.quantity)).length }));
  return <main className="module-shell"><header className="module-header"><div><p className="eyebrow">AUDITORIA CONTRATUAL</p><h1>Conformidade</h1><p className="module-subtitle">Visão consolidada dos anexos, estoque, CA e controles técnicos.</p></div><a className="secondary-button" href="/contract-requirements"><ClipboardCheck size={16} /> Ver requisitos</a></header>{error && <div className="feedback error-feedback"><ShieldAlert size={17} /> {error}</div>}{loading ? <div className="module-loading"><LoaderCircle className="spin" size={22} /> Carregando conformidade...</div> : <><section className="module-summary"><div><PackageCheck size={18} /><strong>{rows.length}</strong><span>requisitos importados</span></div><div><ShieldAlert size={18} /><strong>{stockIssues}</strong><span>faltas de estoque</span></div><div><FileWarning size={18} /><strong>{caIssues}</strong><span>pendências de CA</span></div><div><ClipboardCheck size={18} /><strong>{testIssues}</strong><span>itens com ensaio obrigatório</span></div></section><section className="panel module-table-card"><div className="panel-header"><div><h2>Resumo por anexo</h2><p>Use os detalhes do anexo para regularizar estoque e documentação.</p></div></div><div className="table-wrap"><table><thead><tr><th>ANEXO</th><th>REQUISITOS</th><th>FALTAS DE ESTOQUE</th><th>STATUS</th></tr></thead><tbody>{byAnnex.map((item) => <tr key={item.annex}><td><strong>{item.annex}</strong></td><td>{item.count}</td><td className={item.missing ? "history-negative" : "history-positive"}>{item.missing}</td><td><span className={`status-pill ${item.missing ? "danger" : "success"}`}>{item.missing ? "Ação necessária" : "Estoque atende"}</span></td></tr>)}</tbody></table></div></section><section className="panel module-table-card"><div className="panel-header"><div><h2>Próximas ações</h2><p>Os ensaios e treinamentos devem ser conferidos antes da liberação operacional.</p></div></div><div className="alert-list"><a className="alert-item" href="/tests"><span className="alert-icon calendar"><ClipboardCheck size={16} /></span><div><strong>Ensaios e laudos</strong><p>Registrar resultados, ART e referências dos documentos dos itens isolantes.</p></div></a><a className="alert-item" href="/training-compliance"><span className="alert-icon"><FileWarning size={16} /></span><div><strong>Treinamentos</strong><p>Conferir validade dos cursos obrigatórios por função.</p></div></a><a className="alert-item" href="/units"><span className="alert-icon swap"><PackageCheck size={16} /></span><div><strong>Unidades físicas</strong><p>Completar série, lote, tamanho, fabricante e validade do inventário real.</p></div></a></div></section></>}</main>;
}
