"use client";

import { FormEvent, useEffect, useState } from "react";
import { ArrowLeft, Check, ClipboardList, Plus, X } from "lucide-react";
import Link from "next/link";
import { createClient } from "@/lib/supabase/client";

type MaterialOption = { id: string; name: string; internal_code: string; unit: string };
type EntryForm = { material_id: string; lot_number: string; quantity: string; entry_date: string; manufactured_at: string; expires_at: string; invoice_number: string; notes: string };
const initialForm: EntryForm = { material_id: "", lot_number: "", quantity: "1", entry_date: new Date().toISOString().slice(0, 10), manufactured_at: "", expires_at: "", invoice_number: "", notes: "" };

export default function EntriesPage() {
  const [materials, setMaterials] = useState<MaterialOption[]>([]); const [form, setForm] = useState<EntryForm>(initialForm); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [error, setError] = useState(""); const [success, setSuccess] = useState("");
  async function loadMaterials() { const { data, error: loadError } = await createClient().from("materials").select("id, name, internal_code, unit").eq("status", "active").order("name"); if (loadError) setError(loadError.message); else setMaterials((data ?? []) as MaterialOption[]); setLoading(false); }
  useEffect(() => { const timer = window.setTimeout(() => { void loadMaterials(); }, 0); return () => window.clearTimeout(timer); }, []);
  function update(field: keyof EntryForm, value: string) { setForm((current) => ({ ...current, [field]: value })); }
  async function submit(event: FormEvent) { event.preventDefault(); setError(""); setSuccess(""); setSaving(true); const { error: entryError } = await createClient().rpc("register_stock_entry", { p_material_id: form.material_id, p_lot_number: form.lot_number, p_quantity: Number(form.quantity), p_entry_date: form.entry_date || null, p_manufactured_at: form.manufactured_at || null, p_expires_at: form.expires_at || null, p_invoice_number: form.invoice_number || null, p_notes: form.notes || null }); if (entryError) setError(entryError.message); else { setSuccess("Entrada registrada e estoque atualizado com sucesso."); setForm({ ...initialForm, entry_date: new Date().toISOString().slice(0, 10) }); } setSaving(false); }
  return <main className="module-shell"><header className="module-header"><div><p className="eyebrow">MOVIMENTAÇÃO DE ESTOQUE</p><h1>Entrada de materiais</h1><p className="module-subtitle">Registre lotes recebidos e mantenha o histórico de entradas.</p></div><Link className="secondary-button" href="/stock"><ArrowLeft size={16} /> Ver estoque</Link></header>{success && <div className="feedback success-feedback"><Check size={17} /> {success}</div>}{error && <div className="feedback error-feedback"><X size={17} /> {error}</div>}<section className="panel entry-card"><div className="entry-intro"><div className="entry-icon"><ClipboardList size={22} /></div><div><h2>Dados da entrada</h2><p>O sistema criará o lote e a movimentação de entrada em uma única operação.</p></div></div><form className="material-form" onSubmit={submit}><div className="form-grid two"><label>Material<select value={form.material_id} onChange={(event) => update("material_id", event.target.value)} required disabled={loading}><option value="">Selecione um material</option>{materials.map((material) => <option key={material.id} value={material.id}>{material.internal_code} · {material.name} ({material.unit})</option>)}</select></label><label>Número do lote<input value={form.lot_number} onChange={(event) => update("lot_number", event.target.value)} placeholder="Ex.: LOTE-2026-001" required /></label></div><div className="form-grid three"><label>Quantidade recebida<input type="number" min="1" value={form.quantity} onChange={(event) => update("quantity", event.target.value)} required /></label><label>Data da entrada<input type="date" value={form.entry_date} onChange={(event) => update("entry_date", event.target.value)} required /></label><label>Nota fiscal<input value={form.invoice_number} onChange={(event) => update("invoice_number", event.target.value)} placeholder="NF-000123" /></label></div><div className="form-grid two"><label>Data de fabricação<input type="date" value={form.manufactured_at} onChange={(event) => update("manufactured_at", event.target.value)} /></label><label>Data de validade do lote<input type="date" value={form.expires_at} onChange={(event) => update("expires_at", event.target.value)} /></label></div><label>Observações<textarea value={form.notes} onChange={(event) => update("notes", event.target.value)} placeholder="Fornecedor, conferência ou outras observações" rows={3} /></label><div className="modal-actions"><button type="reset" className="secondary-button" onClick={() => setForm(initialForm)}>Limpar</button><button className="primary-button" disabled={saving || loading || !materials.length}>{saving ? "Registrando..." : "Registrar entrada"}<Plus size={16} /></button></div></form></section></main>;
}

