"use client";

import { ArrowDownToLine, ArrowUpRight, Bell, Boxes, CalendarClock, ChevronDown, CircleHelp, ClipboardCheck, ClipboardList, LayoutDashboard, Menu, PackageCheck, Search, Settings, SlidersHorizontal, ShieldCheck, Users, Wallet, X } from "lucide-react";
import Link from "next/link";
import { usePathname } from "next/navigation";
import { useEffect, useState } from "react";
import { createClient } from "@/lib/supabase/client";

type MenuItem = readonly [string, typeof LayoutDashboard, string];
type MenuSection = { label: string; items: readonly MenuItem[] };
const menuSections: readonly MenuSection[] = [
  { label: "Visão geral", items: [["Dashboard", LayoutDashboard, "/"]] },
  { label: "Cadastros", items: [["Materiais", Boxes, "/materials"], ["Funcionários", Users, "/employees"], ["Equipes", Users, "/teams"], ["Unidades físicas", Boxes, "/units"], ["Listas por função", ClipboardList, "/function-templates"]] },
  { label: "Operações", items: [["Entradas", ClipboardList, "/entries"], ["Entregas", ArrowUpRight, "/deliveries"], ["Devoluções", ArrowDownToLine, "/returns"], ["Solicitações", ClipboardList, "/requests"], ["Estoque", PackageCheck, "/stock"], ["Validades", CalendarClock, "/validities"]] },
  { label: "Conformidade", items: [["Requisitos contratuais", ClipboardCheck, "/contract-requirements"], ["Ensaios", ClipboardCheck, "/tests"], ["Treinamentos", ClipboardCheck, "/training-compliance"], ["Conformidade", ClipboardCheck, "/compliance"], ["CA", ShieldCheck, "/ca"]] },
  { label: "Gestão e análises", items: [["Custos", Wallet, "/costs"], ["Relatórios", ClipboardList, "/reports"], ["Movimentações", SlidersHorizontal, "/movements"], ["Auditoria", ClipboardList, "/audit"]] },
] as const;
const menu = menuSections.flatMap((section) => section.items);
type SearchResult = { id: string; label: string; detail: string | null; href: string; kind: "Material" | "Funcionario" };

export function AppShell({ children }: { children: React.ReactNode }) {
  const pathname = usePathname(); const [mobileMenu, setMobileMenu] = useState(false); const [query, setQuery] = useState(""); const [results, setResults] = useState<SearchResult[]>([]); const [validityCount, setValidityCount] = useState(0);
  useEffect(() => { void Promise.resolve().then(async () => { const supabase = createClient(); const [{ data: lots, error: lotError }, { data: deliveryItems, error: itemError }, { data: returns, error: returnError }] = await Promise.all([supabase.from("material_lots").select("id,expires_at,available_quantity"), supabase.from("delivery_items").select("id,lot_id,quantity"), supabase.from("return_items").select("delivery_item_id,quantity")]); if (lotError || itemError || returnError) { setValidityCount(0); return; } const today = new Date(); today.setHours(0, 0, 0, 0); const isAlert = (expiresAt: string | null) => { if (!expiresAt) return false; const days = Math.ceil((new Date(`${expiresAt}T00:00:00`).getTime() - today.getTime()) / 86400000); return days <= 30; }; const lotMap = new Map((lots ?? []).map((lot) => [lot.id, lot.expires_at])); const returned = new Map<string, number>(); for (const item of returns ?? []) returned.set(item.delivery_item_id, (returned.get(item.delivery_item_id) ?? 0) + Number(item.quantity)); const stockAlerts = (lots ?? []).filter((lot) => Number(lot.available_quantity) > 0 && isAlert(lot.expires_at)).length; const assignedAlerts = (deliveryItems ?? []).filter((item) => Number(item.quantity) > (returned.get(item.id) ?? 0) && item.lot_id && isAlert(lotMap.get(item.lot_id) ?? null)).length; setValidityCount(stockAlerts + assignedAlerts); }); }, []);
  useEffect(() => { const term = query.trim(); if (term.length < 2) { setResults([]); return; } const timer = window.setTimeout(async () => { const supabase = createClient(); const pattern = `%${term.replaceAll("%", "\\%").replaceAll("_", "\\_")}%`; const [{ data: materialData }, { data: employeeData }] = await Promise.all([supabase.from("materials").select("id,name,internal_code").or(`name.ilike.${pattern},internal_code.ilike.${pattern}`).limit(5), supabase.from("employees").select("id,full_name,registration").or(`full_name.ilike.${pattern},registration.ilike.${pattern}`).limit(5)]); setResults([...((materialData ?? []).map((item) => ({ id: item.id, label: item.name, detail: item.internal_code, href: "/materials", kind: "Material" as const }))), ...((employeeData ?? []).map((item) => ({ id: item.id, label: item.full_name, detail: item.registration, href: `/employees/${item.id}`, kind: "Funcionario" as const })))]); }, 220); return () => window.clearTimeout(timer); }, [query]);
  if (pathname === "/login" || pathname === "/reset-password" || pathname.startsWith("/medidas/") || pathname === "/portal") return <>{children}</>;
  function closeSearch() { setQuery(""); setResults([]); }
  return <div className="app-shell"><aside className={`sidebar ${mobileMenu ? "open" : ""}`}><div className="brand"><div className="brand-mark"><ShieldCheck size={22} /></div><div><strong>EPIS<span>+</span></strong><small>Gestao inteligente</small></div><button className="close-menu" onClick={() => setMobileMenu(false)} aria-label="Fechar menu"><X size={20} /></button></div><div className="workspace-label">MENU PRINCIPAL</div><div className="sidebar-sections">{menuSections.map((section) => <section className="sidebar-section" key={section.label}><h2>{section.label}</h2><nav>{section.items.map(([label, Icon, href]) => <Link className={pathname === href || (href !== "/" && pathname.startsWith(`${href}/`)) ? "active" : ""} href={href} key={label} onClick={() => setMobileMenu(false)}><Icon size={18} /><span>{label}</span>{label === "Validades" && validityCount > 0 && <b className="nav-count">{validityCount}</b>}</Link>)}</nav></section>)}</div><div className="sidebar-bottom"><Link href="/settings"><Settings size={18} /><span>Configuracoes</span></Link><Link href="/help"><CircleHelp size={18} /><span>Central de ajuda</span></Link><div className="user-mini"><div className="avatar avatar-dark">SA</div><div><strong>Samuel Albuquerque</strong><small>Administrador</small></div><ChevronDown size={15} /></div></div></aside><main className="main-content"><header className="topbar"><button className="menu-toggle" onClick={() => setMobileMenu(true)} aria-label="Abrir menu"><Menu size={22} /></button><div className="breadcrumb"><span>Visao geral</span><span>/</span><strong>{pathname === "/" ? "Dashboard" : menu.find((item) => item[2] === pathname)?.[0] ?? "EPIS+"}</strong></div><div className="top-actions"><div className="global-search"><div className="search"><Search size={18} /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Buscar materiais, funcionarios..." aria-label="Buscar materiais ou funcionarios" /></div>{query.trim().length >= 2 && <div className="search-results">{results.length ? results.map((item) => <Link href={item.href} key={`${item.kind}-${item.id}`} onClick={closeSearch}><strong>{item.label}</strong><span>{item.kind} · {item.detail || "Sem detalhe"}</span></Link>) : <span className="search-empty">Nenhum resultado encontrado.</span>}</div>}</div><Link className="icon-button notification" href="/validities" aria-label="Ver alertas de validade"><Bell size={19} /><i /></Link><div className="profile"><div className="avatar avatar-blue">SA</div><div><strong>Samuel Albuquerque</strong><small>Administrador</small></div><ChevronDown size={15} /></div></div></header>{children}</main></div>;
}
