"use client";

import Link from "next/link";
import { BookOpenCheck, CheckCircle2, ClipboardList, LoaderCircle, ShieldAlert } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import { createClient } from "@/lib/supabase/client";

type Requirement = { id: string; function_group: string; course_name: string; source_annex: string; mandatory: boolean; validity_months: number | null; notes: string | null };
type Employee = { id: string; full_name: string; job_title: string | null; function_name: string | null };
type Course = { employee_id: string; name: string; expires_at: string | null };
function normalize(value: string) { return value.normalize("NFD").replace(/[\u0300-\u036f]/g, "").toLowerCase(); }
function matchesGroup(employee: Employee, group: string) { if (group === "Todos os grupos") return true; const text = normalize(`${employee.job_title ?? ""} ${employee.function_name ?? ""}`); return text.includes(normalize(group)) || (group === "Poda" && text.includes("pod")) || (group === "Operador de Guindauto" && (text.includes("munck") || text.includes("guindauto"))); }
function validCourse(courses: Course[], employeeId: string, requirement: Requirement) { return courses.some((course) => course.employee_id === employeeId && normalize(course.name).includes(normalize(requirement.course_name.split(" - ")[0])) && (!course.expires_at || course.expires_at >= new Date().toISOString().slice(0, 10))); }

export default function TrainingCompliancePage() {
  const [requirements, setRequirements] = useState<Requirement[]>([]); const [employees, setEmployees] = useState<Employee[]>([]); const [courses, setCourses] = useState<Course[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  useEffect(() => { async function load() { const supabase = createClient(); const [{ data: requirementData, error: requirementError }, { data: employeeData, error: employeeError }, { data: courseData, error: courseError }] = await Promise.all([supabase.from("contract_training_requirements").select("id, function_group, course_name, source_annex, mandatory, validity_months, notes").order("function_group").order("course_name"), supabase.from("employees").select("id, full_name, job_title, function_name").eq("status", "active").order("full_name"), supabase.from("employee_courses").select("employee_id, name, expires_at")]); if (requirementError || employeeError || courseError) setError((requirementError ?? employeeError ?? courseError)?.message ?? "Não foi possível carregar a matriz de treinamentos."); setRequirements((requirementData ?? []) as Requirement[]); setEmployees((employeeData ?? []) as Employee[]); setCourses((courseData ?? []) as Course[]); setLoading(false); } void load(); }, []);
  const rows = useMemo(() => requirements.map((requirement) => { const applicable = employees.filter((employee) => matchesGroup(employee, requirement.function_group)); const completed = applicable.filter((employee) => validCourse(courses, employee.id, requirement)).length; return { requirement, applicable: applicable.length, completed, pending: Math.max(applicable.length - completed, 0) }; }), [requirements, employees, courses]);
  const pending = rows.reduce((sum, row) => sum + row.pending, 0); const covered = rows.reduce((sum, row) => sum + row.completed, 0);
  return <main className="module-shell"><header className="module-header"><div><p className="eyebrow">CONFORMIDADE CONTRATUAL</p><h1>Treinamentos obrigatórios</h1><p className="module-subtitle">Matriz inicial do Anexo 03 vinculada aos cursos cadastrados nos colaboradores.</p></div><Link className="secondary-button" href="/employees"><ClipboardList size={16} /> Funcionários</Link></header>{error && <div className="feedback error-feedback"><ShieldAlert size={17} /> {error}</div>}{loading ? <div className="module-loading"><LoaderCircle className="spin" size={22} /> Carregando matriz...</div> : <><section className="module-summary"><div><BookOpenCheck size={18} /><strong>{requirements.length}</strong><span>requisitos cadastrados</span></div><div><CheckCircle2 size={18} /><strong>{covered}</strong><span>coberturas identificadas</span></div><div><ShieldAlert size={18} /><strong>{pending}</strong><span>pendências por colaborador</span></div><div><ClipboardList size={18} /><strong>{employees.length}</strong><span>colaboradores ativos</span></div></section><section className="panel module-table-card"><div className="panel-header"><div><h2>Matriz de treinamentos</h2><p>O cadastro dos cursos deve ser validado pelo responsável de segurança antes da liberação operacional.</p></div></div>{rows.length ? <div className="table-wrap"><table><thead><tr><th>GRUPO / FUNÇÃO</th><th>CURSO</th><th>VALIDADE</th><th>APLICÁVEL</th><th>COBERTOS</th><th>PENDÊNCIAS</th></tr></thead><tbody>{rows.map((row) => <tr key={row.requirement.id}><td><strong>{row.requirement.function_group}</strong><small>{row.requirement.source_annex}</small></td><td><strong>{row.requirement.course_name}</strong><small>{row.requirement.notes}</small></td><td>{row.requirement.validity_months ? `${row.requirement.validity_months} meses` : "Conforme curso"}</td><td>{row.applicable}</td><td><span className="status-pill success">{row.completed}</span></td><td><span className={`status-pill ${row.pending ? "danger" : "success"}`}>{row.pending || "OK"}</span></td></tr>)}</tbody></table></div> : <div className="empty-state"><BookOpenCheck size={27} /><strong>Nenhum requisito cadastrado</strong><span>Cadastre os requisitos contratuais para acompanhar a conformidade.</span></div>}</section></>}</main>;
}
