"use client";

import { FormEvent, useEffect, useState } from "react";
import { Boxes, Check, Plus, Trash2, X } from "lucide-react";
import { createClient } from "@/lib/supabase/client";

type Material = { id: string; name: string; internal_code: string; unit: string };
type Variant = { id: string; material_id: string; name: string; size: string | null; color: string | null; model: string | null; sku: string | null; unit_cost: number; active: boolean };
const empty = { material_id: "", name: "", size: "", color: "", model: "", sku: "", unit_cost: "0" };
export default function VariantsPage() { const [materials, setMaterials] = useState<Material[]>([]); const [variants, setVariants] = useState<Variant[]>([]); const [form, setForm] = useState(empty); const [error, setError] = useState(""); const [success, setSuccess] = useState("");
  async function load() { const supabase = createClient(); const [{ data: materialData }, { data: variantData, error: variantError }] = await Promise.all([supabase.from("materials").select("id,name,internal_code,unit").eq("status", "active").order("name"), supabase.from("material_variants").select("id,material_id,name,size,color,model,sku,unit_cost,active,materials(name,internal_code)").order("created_at", { ascending: false })]); if (variantError) setError(variantError.message); setMaterials((materialData ?? []) as Material[]); setVariants((variantData ?? []) as Variant[]); }
  useEffect(() => { void load(); }, []);
  async function save(event: FormEvent) { event.preventDefault(); setError(""); setSuccess(""); const supabase = createClient(); const { data: auth } = await supabase.auth.getUser(); const { data: profile } = await supabase.from("profiles").select("organization_id").eq("id", auth.user?.id ?? "").single(); const { error: saveError } = await supabase.from("material_variants").insert({ ...form, organization_id: profile?.organization_id, unit_cost: Number(form.unit_cost) || 0, size: form.size || null, color: form.color || null, model: form.model || null, sku: form.sku || null }); if (saveError) setError(saveError.message); else { setForm(empty); setSuccess("VariaÃ§Ã£o cadastrada."); await load(); } }
  async function remove(id: string) { const { error: removeError } = await createClient().from("material_variants").update({ active: false }).eq("id", id); if (removeError) setError(removeError.message); else setVariants((current) => current.filter((item) => item.id !== id)); }
  return <main className="module-shell"><header className="module-header"><div><p className="eyebrow">ESTOQUE POR VARIAÃ‡ÃƒO</p><h1>Tamanhos e modelos</h1><p className="module-subtitle">Controle botinas, capacetes, uniformes e ferramentais individualmente.</p></div></header>{success && <div className="feedback success-feedback"><Check size={17} /> {success}</div>}{error && <div className="feedback error-feedback"><X size={17} /> {error}</div>}<section className="panel edit-employee-card"><form className="material-form" onSubmit={save}><div className="form-grid two"><label>Material<select value={form.material_id} onChange={(e) => setForm({ ...form, material_id: e.target.value })} required><option value="">Selecione</option>{materials.map((item) => <option key={item.id} value={item.id}>{item.internal_code} Â· {item.name}</option>)}</select></label><label>Nome da variaÃ§Ã£o<input value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} placeholder="Ex.: NÃºmero 40 / Aba total" required /></label></div><div className="form-grid four"><label>Tamanho<input value={form.size} onChange={(e) => setForm({ ...form, size: e.target.value })} /></label><label>Cor<input value={form.color} onChange={(e) => setForm({ ...form, color: e.target.value })} /></label><label>Modelo<input value={form.model} onChange={(e) => setForm({ ...form, model: e.target.value })} /></label><label>Custo unitÃ¡rio<input type="number" min="0" step="0.01" value={form.unit_cost} onChange={(e) => setForm({ ...form, unit_cost: e.target.value })} /></label></div><button className="primary-button"><Plus size={16} /> Cadastrar variaÃ§Ã£o</button></form></section><section className="panel module-table-card"><div className="panel-header"><div><h2>VariaÃ§Ãµes cadastradas</h2><p>{variants.length} item(ns)</p></div></div><div className="table-wrap"><table><thead><tr><th>MATERIAL</th><th>VARIAÃ‡ÃƒO</th><th>TAMANHO</th><th>CUSTO</th><th>AÃ‡ÃƒO</th></tr></thead><tbody>{variants.map((item) => <tr key={item.id}><td><div className="material-cell"><div className="material-type-icon epi"><Boxes size={16} /></div><strong>{(item as Variant & { materials?: { name: string } }).materials?.name || item.material_id}</strong></div></td><td>{item.name}</td><td>{item.size || "â€”"}</td><td>R$ {Number(item.unit_cost).toFixed(2).replace(".", ",")}</td><td><button className="action-button" onClick={() => void remove(item.id)}><Trash2 size={14} /> Desativar</button></td></tr>)}</tbody></table>{!variants.length && <div className="empty-state"><Boxes size={27} /><strong>Nenhuma variaÃ§Ã£o cadastrada</strong><span>Comece por materiais com numeraÃ§Ã£o ou modelos diferentes.</span></div>}</div></section></main>;
}

