"use client";

import { useEffect, useMemo, useState } from "react";
import { ArrowLeft, Calculator, LoaderCircle, Wallet } from "lucide-react";
import Link from "next/link";
import { createClient } from "@/lib/supabase/client";

type Lot = { material_id: string; received_quantity: number; available_quantity: number; unit_cost: number; material: { name: string; internal_code: string; minimum_stock: number; unit: string } | null };
type MaterialCost = Lot & { totalCost: number; availableCost: number };
function money(value: number) { return `R$ ${value.toFixed(2).replace(".", ",")}`; }

export default function CostsPage() {
  const [lots, setLots] = useState<Lot[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  useEffect(() => { async function load() { const { data, error: loadError } = await createClient().from("material_lots").select("material_id,received_quantity,available_quantity,unit_cost,material:materials(name,internal_code,minimum_stock,unit)"); if (loadError) setError(loadError.message); else setLots((data ?? []) as unknown as Lot[]); setLoading(false); } void load(); }, []);
  const byMaterial = useMemo(() => { const grouped = new Map<string, MaterialCost>(); lots.forEach((lot) => { const received = Number(lot.received_quantity); const available = Number(lot.available_quantity); const unitCost = Number(lot.unit_cost) || 0; const current = grouped.get(lot.material_id); if (current) { current.received_quantity += received; current.available_quantity += available; current.totalCost += received * unitCost; current.availableCost += available * unitCost; } else grouped.set(lot.material_id, { ...lot, received_quantity: received, available_quantity: available, unit_cost: unitCost, totalCost: received * unitCost, availableCost: available * unitCost }); }); return [...grouped.values()]; }, [lots]);
  const spent = lots.reduce((sum, lot) => sum + Number(lot.received_quantity) * (Number(lot.unit_cost) || 0), 0); const current = lots.reduce((sum, lot) => sum + Number(lot.available_quantity) * (Number(lot.unit_cost) || 0), 0); const forecast = byMaterial.reduce((sum, lot) => { const missing = Math.max(0, Number(lot.material?.minimum_stock ?? 0) - lot.available_quantity); const weightedUnitCost = lot.received_quantity > 0 ? lot.totalCost / lot.received_quantity : 0; return sum + missing * weightedUnitCost; }, 0);
  return <main className="module-shell"><header className="module-header"><div><p className="eyebrow">GESTÃO FINANCEIRA</p><h1>Custos do estoque</h1><p className="module-subtitle">Acompanhe gastos de aquisição, valor atual e reposição prevista.</p></div><Link className="secondary-button" href="/"><ArrowLeft size={16} /> Dashboard</Link></header>{error && <div className="feedback error-feedback">{error}</div>}{loading ? <div className="module-loading"><LoaderCircle className="spin" size={22} /> Calculando custos...</div> : <><section className="module-summary"><div><Wallet size={18} /><strong>{money(spent)}</strong><span>Total adquirido</span></div><div><Calculator size={18} /><strong>{money(current)}</strong><span>Valor em estoque</span></div><div><Wallet size={18} /><strong>{money(forecast)}</strong><span>Reposição prevista</span></div></section><section className="panel module-table-card"><div className="panel-header"><div><h2>Composição por material</h2><p>Custos calculados com base nos lotes recebidos.</p></div></div><div className="table-wrap"><table><thead><tr><th>MATERIAL</th><th>ADQUIRIDO</th><th>EM ESTOQUE</th><th>CUSTO UNITÁRIO MÉDIO</th><th>VALOR TOTAL</th><th>REPOSIÇÃO PREVISTA</th></tr></thead><tbody>{byMaterial.map((lot) => { const weightedUnitCost = lot.received_quantity > 0 ? lot.totalCost / lot.received_quantity : 0; const missing = Math.max(0, Number(lot.material?.minimum_stock ?? 0) - lot.available_quantity); return <tr key={lot.material_id}><td><strong>{lot.material?.name || "Material"}</strong><small>{lot.material?.internal_code || "Sem código"}</small></td><td>{lot.received_quantity} {lot.material?.unit}</td><td>{lot.available_quantity} {lot.material?.unit}</td><td>{money(weightedUnitCost)}</td><td>{money(lot.totalCost)}</td><td>{money(missing * weightedUnitCost)}</td></tr>; })}</tbody></table>{!byMaterial.length && <div className="empty-state"><strong>Nenhuma entrada com custo informada</strong><span>Informe o custo unitário nas entradas para alimentar este painel.</span></div>}</div></section></>}</main>;
}
