do $$
declare
  org_id uuid := '4dc792c1-5087-4eea-a806-e2957cd0d09d';
  row_data jsonb;
  v_material_id uuid;
  v_scenario_id uuid;
  material_type public.material_type;
  material_category text;
begin
  for row_data in select * from jsonb_array_elements('[{"number":1,"description":"Capacete para motociclista com queixeira e viseira","category":"ACESS","scope":"IND","unit":"PÃ§","quantities":1},{"number":2,"description":"Luva para Motociclista","category":"ACESS","scope":"IND","unit":"Par","quantities":1},{"number":3,"description":"Joelheira para Motociclista","category":"ACESS","scope":"IND","unit":"Par","quantities":1},{"number":4,"description":"Cotoveleira para Motociclista","category":"ACESS","scope":"IND","unit":"Par","quantities":1},{"number":5,"description":"Botina de seguranÃ§a cano longo","category":"ACESS","scope":"IND","unit":"pÃ§","quantities":1},{"number":6,"description":"Teste neon/detector de tensÃ£o tipo caneta, c/sinal de detecÃ§Ã£o luminosa e sonora","category":"FER","scope":"IND","unit":"PÃ§","quantities":1},{"number":7,"description":"Camisa manga longa com fita reletiva","category":"EPI","scope":"IND","unit":"PÃ§","quantities":2},{"number":8,"description":"CalÃ§a com fita relfetiva","category":"EPI","scope":"COL","unit":"PÃ§","quantities":2},{"number":9,"description":"Bloqueador solar","category":"ACESS","scope":"COL","unit":"PÃ§","quantities":2},{"number":10,"description":"Ã“culos de seguranÃ§a lente escura","category":"EPI","scope":"IND","unit":"UND","quantities":2},{"number":11,"description":"Bota de pvc","category":"EPI","scope":"IND","unit":"Par","quantities":2},{"number":12,"description":"Conjunto impermeÃ¡vel","category":"EPI","scope":"IND","unit":"UND","quantities":2}]'::jsonb) loop
    material_type := case row_data->>'category' when 'EPI' then 'EPI' else 'FERRAMENTAL' end;
    material_category := case row_data->>'category' when 'EPI' then 'EPI' when 'FER' then 'FERRAMENTAL' else 'ACESSORIO' end;
    insert into public.materials (organization_id, internal_code, name, type, unit, ca_number, minimum_stock, status, contract_item_code, contract_item_number, contract_category, usage_scope, contract_source, contract_specification, ca_required, test_required, test_type, test_interval_months, report_required, art_required, notes)
    values (org_id, 'A07-' || lpad((row_data->>'number')::text, 3, '0'), trim(row_data->>'description'), material_type, case upper(row_data->>'unit') when 'PAR' then 'PAR' else 'un.' end, case when material_type = 'EPI' then 'PENDENTE' else null end, 0, 'active', 'A07-' || lpad((row_data->>'number')::text, 3, '0'), (row_data->>'number')::int, material_category, case row_data->>'scope' when 'IND' then 'individual' else 'coletivo' end, 'Contrato WS 93000 - Anexo 07', trim(row_data->>'description'), material_type = 'EPI', material_type = 'EPI', case when material_type = 'EPI' then 'dielectric' else null end, case when material_type = 'EPI' then 12 else null end, material_type = 'EPI', material_type = 'EPI', 'Item importado integralmente do Anexo 07. Validar cadastro físico, fabricante, CA e ensaio.')
    on conflict (organization_id, contract_item_code) where contract_item_code is not null do update set name = excluded.name, type = excluded.type, unit = excluded.unit, contract_item_number = excluded.contract_item_number, contract_category = excluded.contract_category, usage_scope = excluded.usage_scope, contract_specification = excluded.contract_specification, ca_required = excluded.ca_required, test_required = excluded.test_required, test_type = excluded.test_type, test_interval_months = excluded.test_interval_months, report_required = excluded.report_required, art_required = excluded.art_required;
    select id into v_material_id from public.materials where organization_id = org_id and contract_item_code = 'A07-' || lpad((row_data->>'number')::text, 3, '0');
    select id into v_scenario_id from public.contract_scenarios where organization_id = org_id and code = 'MOTOCICLISTA';
    insert into public.contract_requirements (organization_id, scenario_id, material_id, source_annex, source_item_number, quantity, unit, usage_scope, notes)
    values (org_id, v_scenario_id, v_material_id, 'Anexo 07', (row_data->>'number')::int, coalesce((row_data->'quantities'->>0)::int, 1), case upper(row_data->>'unit') when 'PAR' then 'PAR' else 'un.' end, case row_data->>'scope' when 'IND' then 'individual' else 'coletivo' end, 'Quantidade mínima importada do Anexo 07.')
    on conflict (scenario_id, material_id, usage_scope) do update set quantity = excluded.quantity, unit = excluded.unit, source_item_number = excluded.source_item_number, notes = excluded.notes;
  end loop;
end $$;
