"use client";

import { FormEvent, useEffect, useState } from "react";
import { Check, LoaderCircle, Ruler, ShieldCheck, X } from "lucide-react";
import { useParams } from "next/navigation";
const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL ?? "https://uedqxkzprueezjarhzql.supabase.co";
const supabasePublishableKey = "sb_publishable_9l2tSpFY9qHdAysv4P4ECw_rzqqgDbY";
async function publicRpc<T>(functionName: string, body: Record<string, unknown>) {
  const response = await fetch(`${supabaseUrl}/rest/v1/rpc/${functionName}`, { method: "POST", headers: { apikey: supabasePublishableKey, Authorization: `Bearer ${supabasePublishableKey}`, "Content-Type": "application/json" }, body: JSON.stringify(body) });
  if (!response.ok) throw new Error(`RPC ${response.status}`);
  return response.json() as Promise<T>;
}

type Form = { shirt: string; pants: string; shoe: string; helmet: string; glove: string; notes: string };
const empty: Form = { shirt: "", pants: "", shoe: "", helmet: "", glove: "", notes: "" };

export default function PublicMeasurementsPage() {
  const { token } = useParams<{ token: string }>(); const [name, setName] = useState(""); const [form, setForm] = useState<Form>(empty); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [success, setSuccess] = useState(false); const [error, setError] = useState("");
  useEffect(() => { const routeToken = token || window.location.pathname.split("/").filter(Boolean).pop() || ""; async function load() { try { const data = await publicRpc<Array<{ employee_name: string; completed_at: string | null }>>("get_measurement_request", { p_token: routeToken }); const row = data?.[0]; if (!row) setError("Este link  invlido ou expirou. Solicite um novo link ao responsvel."); else if (row.completed_at) setError("Este link j foi utilizado. Solicite um novo link ao responsvel."); else if (row.completed_at) setError("Este link j\\u00e1 foi utilizado. Solicite um novo link ao responsavel."); else setName(row.employee_name); } catch { setError("No foi possvel conectar ao Supabase. Tente abrir o link novamente."); } setLoading(false); } if (routeToken) void load(); else { setError("Este link  invlido ou expirou. Solicite um novo link ao responsvel."); setLoading(false); } }, [token]);
  function update(field: keyof Form, value: string) { setForm((current) => ({ ...current, [field]: value })); }
  async function submit(event: FormEvent) { event.preventDefault(); setSaving(true); setError(""); try { await publicRpc("submit_measurement_request", { p_token: token || window.location.pathname.split("/").filter(Boolean).pop(), p_shirt_size: form.shirt, p_pants_size: form.pants, p_shoe_size: form.shoe, p_helmet_size: form.helmet, p_glove_size: form.glove, p_notes: form.notes }); setSuccess(true); } catch { setError("No foi possvel registrar as medidas. Solicite um novo link ao responsvel."); } setSaving(false); }
  return <main className="public-measurements"><section className="public-measurement-card"><div className="public-brand"><ShieldCheck size={22} /><strong>EPIS<span>+</span></strong></div>{loading ? <div className="module-loading"><LoaderCircle className="spin" size={22} /> Carregando formulrio...</div> : error && !name ? <div className="public-feedback error-feedback"><X size={18} /> {error}</div> : success ? <div className="public-success"><Check size={36} /><h1>Medidas enviadas!</h1><p>Obrigado, {name}. Seus dados foram encaminhados para o controle de equipamentos.</p></div> : <><div className="public-title"><Ruler size={26} /><p>PERFIL DE EQUIPAMENTOS</p><h1>Ol, {name}</h1><span>Informe suas medidas para que os equipamentos e uniformes sejam separados corretamente.</span></div><form className="material-form public-form" onSubmit={submit}><div className="form-grid two"><label>Camiseta / uniforme<input value={form.shirt} onChange={(e) => update("shirt", e.target.value)} placeholder="Ex.: M" /></label><label>Cala<input value={form.pants} onChange={(e) => update("pants", e.target.value)} placeholder="Ex.: 42" /></label></div><div className="form-grid three"><label>Calado / botina<input value={form.shoe} onChange={(e) => update("shoe", e.target.value)} placeholder="Ex.: 40" /></label><label>Capacete<input value={form.helmet} onChange={(e) => update("helmet", e.target.value)} placeholder="Ex.: 58" /></label><label>Luvas<input value={form.glove} onChange={(e) => update("glove", e.target.value)} placeholder="Ex.: 9 / G" /></label></div><label>Observaes<textarea value={form.notes} onChange={(e) => update("notes", e.target.value)} rows={3} placeholder="Prefer\\u00eancias ou medidas especiais" /></label>{error && <div className="public-feedback error-feedback"><X size={17} /> {error}</div>}<button className="primary-button" disabled={saving}>{saving ? "Enviando..." : "Enviar minhas medidas"}<Check size={16} /></button></form></>}</section></main>;
}

